tasks:
  - name: Pull Images
    init: ./services create

ports:
  - name: Orion
    description: Context Broker
    port: 1026
    onOpen: notify
  - name: Tutorial App
    description: Web app displaying context data
    port: 3000
    onOpen: open-preview
  - name: Tutorial Devices
    description: Dummy IoT Sensors over HTTP
    port: 3001
    onOpen: ignore
  - name: MongoDB
    description: Database for Orion
    port: 27017
    onOpen: ignore